* Introduction

Have you ever found yourself mindlessley clicking through the AWS web
console for the 100th time today to drill into the latest Cloudwatch
log stream?  Have you ever found yourself downloading a file through
the AWS CLI, editing it in Emacs, then switching back to the command
line to re-upload it?  Did you dream of a better way? An Emacs way?
axe wants to be that better way.

axe is an interface for working with AWS resources that is unashamedly
inspired my Magit.  axe aspires to provide a frontend alternative to
the AWS web console and CLI with Emacs-ergonomics for working with the
many AWS services and their constituent resources.  In doing so, it
also tries to provide more fluid workflows for many tasks that are
tediously typed out through the AWS CLI.

A major design decision of axe was whether to implement against the
AWS CLI, AWS HTTP APIs.  In order to compatability issues with
CLI versions and dependencies on extra-Emacs utilities, the decision
to leverage the AWS HTTP APIs was made.  In the future, it may be
decided to split the AWS API functionality off into its own package to
provided an independent AWS SDK for elisp.

Many AWS APIs return paged requests, so axe provides a functionality
for asyncronously querying, formatting and appending the paged
responses to a tabulated buffer.  ~axe-list-api-results~ allows the
caller to specify a list format, a function for formatting the result,
a function for custom key bindings and a function for determining the
"next token".  This next token can be used to make a request for the
next page, either automatically (for perhaps tailing a log stream) or
based on a keybinding.  If necessary, a delay can be specified to stay
within resource limitations.

axe is independently developed and in no way affiliated with Amazon or
AWS.  The burden of development and maintenance rests souly on its
author/maintainer.  Comments, recomendations and criticisms are
welcome, but please keep them constructive.  This project started
initially as utilities that were useful for him.

* Installation
* Usage
** Configurations
** S3
*** axe-s3-list-buckets

Displays a table view of all buckets for the current credentials.

Buffer Keybinds:

~l~: List all objects contained in the row at current point.

*** axe-s3-create-bucket

Interactive function that creates a bucket, reading the bucket's name
from the minibuffer.

*** axe-s3-delete-bucket

Interactive function that deletes a bucket, reading the bucket's name
from the minibuffer.

*** axe-s3-list-objects-v2

Interactive function that lists all the objects in a bucket.  The
bucket's name is read from the minbuffer.

Buffer Keybinds:

~d~: Display the object in the row at current point in a new window.
See ~axe-s3-display-object~ for further details.

*** axe-s3-display-object

Interactive function that displays an S3 object.  Reads a bucket name
and object key from the minbuffer.  Sets buffer local variables
~axe-s3-object-key~, ~axe-s3-object-bucket~, and
~axe-s3-object-content-type~.  Uses ~auto-mode-alist~ to try to
determine a mode based on the objects key.  If the object type an
image based on the ~Content Type~ header and its type is capable of
being displayed per ~image-type-available-p~, the data is read and
rendered.  Any unrecognized binary data is simply shown as ~<binary
data>~

*** axe-s3-write-buffer-to-object

Write the contents of the current buffer to an object in S3.  The
object bucket, key and content type are read from the minibuffer.  If
available, bucket and key are prepopulated from ~axe-s3-object-bucket~
and ~axe-s3-object-key~.  The content type will be read if it can't be
guessed by the key's extension or if the buffer local variable
~axe-s3-object-content-type~ is unset.

*** axe-s3-list-objects-in-bucket-at-point

Convenience function that will call ~axe-s3-list-objects-v2~ using the
bucket name found under current point.

** Lambda
** Cloudwatch Logs
* Contributing
